services:
  getafix:
    image: incredibad/getafix:latest
    container_name: getafix
    ports:
      - "4220:4220"
    volumes:
      - getafix_data:/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  getafix_data:
    external: true
